VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CircularCurve"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Alignment.Horizontal")
Option Explicit
Implements IAlignmentElement

' IAlignmentElement Implementation
Private Property Get IAlignmentElement_BeginStationValue() As Double

End Property

Private Property Get IAlignmentElement_EndStationValue() As Double

End Property
